### PR TITLE
chore: upgrade tsconfck to 2.1.0

### LINKED ISSUE #103: Enable Typescript 5.0 compatiblity
The `tsconfck` dependency needs to be updated to at least v2.1.0 in order to meet peer dependency requirements for Typescript 5.0

### PR DESCRIPTION
**Pull request by christopherschroer**
Closes #103

### CODE REVIEW

**Comment by aleclarson** [comment]
Why is this necessary? Semver handles automatic upgrade from 2.0 to 2.1, no?

**Comment by christopherschroer** [comment]
You could also run an update on your lock file to get the latest version of `tsconfck` but some teams may be resistant to doing so for other reasons

**Comment by counterbeing** [comment]
PR looks pretty harmless, any chance we could get a new release? Thanks!

**Comment by aleclarson** [comment]
Released in v4.0.8

**Pull request merged**
