### PR TITLE
feat: support `jsconfig.json` files

### LINKED ISSUE #51: Support `jsconfig.json` files
`tsconfig-paths` v4.0.0 now supports `jsconfig.json` files. (see https://github.com/dividab/tsconfig-paths/pull/199)

https://github.com/dividab/tsconfig-paths/blob/master/CHANGELOG.md#400---2022-05-02

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Closes #51

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
@aleclarson Is there anything I still need to do in order to get this one merged?

**Comment by aleclarson** [comment]
Are you sure the upgrade to `tsconfig-paths@4.0.0` is necessary here?

Also, the VSCode docs say this:
image

So you might need to check for `jsconfig.json` here:
https://github.com/aleclarson/vite-tsconfig-paths/blob/master/src/index.ts#L105

**Comment by MichaelDeBoey** [comment]
@aleclarson I think this one should be fine now?

**Comment by aleclarson** [comment]
Closing in favor of #57 since I don't have permission to push to your repo

Thanks for the contribution!

**Comment by MichaelDeBoey** [comment]
@aleclarson Edits by maintainers are enabled though on my branch, so you should be able to push new things 🤔

**Comment by aleclarson** [comment]
Must have been an issue with Codespaces :)

**Pull request closed without merging**
